all: Board.class AbstractBoard.class BoardArray2D.class BoardArray1D.class Driver.class
Board.class: Board.java
	javac -d . -classpath . Board.java
AbstractBoard.class: AbstractBoard.java
	javac -d . -classpath . AbstractBoard.java
BoardArray2D.class: BoardArray2D.java
	javac -d . -classpath . BoardArray2D.java
BoardArray1D.class: BoardArray1D.java
	javac -d . -classpath . BoardArray1D.java
Driver.class: Driver.java
	javac -d . -classpath . Driver.java
clean:
	rm -f *.class