all: Container.class GTUContainer.class GTUIterator.class GTUConcreteIterator.class GTUVector.class GTUSet.class Main.class
Container.class: Container.java
	javac -d . -classpath . Container.java
GTUContainer.class: GTUContainer.java
	javac -d . -classpath . GTUContainer.java
GTUIterator.class: GTUIterator.java
	javac -d . -classpath . GTUIterator.java
GTUConcreteIterator.class: GTUConcreteIterator.java
	javac -d . -classpath . GTUConcreteIterator.java
GTUVector.class: GTUVector.java
	javac -d . -classpath . GTUVector.java
GTUSet.class: GTUSet.java
	javac -d . -classpath . GTUSet.java
Main.class: Main.java
	javac -d . -classpath . Main.java
clean:
	rm -f *.class